language: rust
rust:
- stable
- beta
- nightly
os:
- linux
- osx
env: TYPE=default RUST_BACKTRACE=1
matrix:
  include:
    - os: linux
      rust: nightly
      env: TYPE=bench RUST_BACKTRACE=1
      script: cargo bench --features asm
    - os: osx
      rust: nightly
      env: TYPE=bench RUST_BACKTRACE=1
      script: cargo bench --features asm
