language: rust
cache: cargo
rust:
- stable
- beta
- nightly
os:
- linux
- osx
env: TYPE=default RUST_BACKTRACE=1
matrix:
  include:
    - os: linux
      rust: nightly
      env: TYPE=bench RUST_BACKTRACE=1
      script: cargo bench --features asm
    - os: osx
      rust: nightly
      env: TYPE=bench RUST_BACKTRACE=1
      script: cargo bench --features asm
    - os: linux
      rust: nightly
      env: TYPE=rustfmt RUST_BACKTRACE=1
      script:
        - cargo install rustfmt -f || exit 0
        - cargo fmt -- --write-mode=diff
    - os: linux
      rust: nightly
      env: TYPE=clippy RUST_BACKTRACE=1
      script:
        - cargo install clippy -f || exit 0
        - cargo clippy
